### ISSUE TITLE
Maximum file size allowed in PrimeVault?

### ISSUE THREAD

**Issue by girish8050517990** [Primechain/yobichain#5]
What is the maximum file size that can be uploaded to the PrimeVault? and is there a way to extend that limit?

**Comment by geekongit** [comment]
The default maximum data size per transaction is 8 MB. But on the multichain level it can be scaled up to 64 MB by modifying the parameter `max-std-op-return-size` in `~/home/yobiuser/.multichain/yobichain/params.dat`. You can do this through `multichain.sh` file.

**Comment by geekongit** [comment]
Well you can't change this parameter once the chain has started. You need to modify the multichain.sh file in such a way that this parameter is set even before the chain starts.

**Comment by girish8050517990** [comment]
I still cannot store more than 2MB even after changing value you mentioned. Can you help please?

**Comment by geekongit** [comment]
You shouldn't modify the parameters of an existing chain. That's why you need to modify the multichain.sh file before running it so as to modify this parameter even before the chain starts running.

Again...
`Note: Since you'll be storing the file data in hex format, the size of the hex data will be higher than the actual file size.`
